import type {Metadata} from "next";
import {Inter, Lato} from "next/font/google"; // Import both fonts
import "./globals.css";

// Configure Lato font
const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
});

// Configure Inter font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
      className={`${lato.variable} ${inter.variable} antialiased`}
    >
    {children}
    </body>
    </html>
  );
}